const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const PAYSTACK_DONATION_LINK='https://paystack.shop/pay/speakout-donate';
const FIREBASE_AI_ENDPOINT='https://us-central1-speaakout-portal.cloudfunctions.net/askJerry';
function applyTheme(t){document.documentElement.dataset.theme=t==='dark'?'dark':'';localStorage.setItem('offorka-theme',t)}
applyTheme(localStorage.getItem('offorka-theme')||'light');
$('#themeBtn')?.addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
const header=$('#siteHeader');window.addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>24),{passive:true});
const menu=$('#menu');function openMenu(){menu?.classList.add('open');menu?.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeMenu(){menu?.classList.remove('open');menu?.setAttribute('aria-hidden','true');document.body.style.overflow=''}$('#openMenu')?.addEventListener('click',openMenu);$$('[data-close-menu]').forEach(el=>el.addEventListener('click',closeMenu));
$$('[data-donate]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();window.open(PAYSTACK_DONATION_LINK,'_blank','noopener,noreferrer')}));
const aiModal=$('#aiModal'),aiMessages=$('#aiMessages'),aiQuestion=$('#aiQuestion');function openAI(){aiModal?.classList.add('open');aiModal?.setAttribute('aria-hidden','false');setTimeout(()=>aiQuestion?.focus(),100)}function closeAI(){aiModal?.classList.remove('open');aiModal?.setAttribute('aria-hidden','true')}$$('[data-open-ai]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openAI()}));$$('[data-close-ai]').forEach(el=>el.addEventListener('click',closeAI));
function addMessage(role,text){const d=document.createElement('div');d.className=`ai-message ${role}`;d.textContent=text;aiMessages?.appendChild(d);if(aiMessages)aiMessages.scrollTop=aiMessages.scrollHeight}
$('#aiForm')?.addEventListener('submit',async e=>{e.preventDefault();const question=aiQuestion?.value.trim();if(!question)return;addMessage('user',question);aiQuestion.value='';addMessage('assistant','Thinking…');const replies=()=>$$('.ai-message.assistant',aiMessages);try{const response=await fetch(FIREBASE_AI_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const data=await response.json();const list=replies(),last=list[list.length-1];last.textContent=response.ok?(data.answer||'Could you share a little more?'):(data.error||'Jerry+ is temporarily unavailable.')}catch{const list=replies(),last=list[list.length-1];last.textContent='Jerry+ is temporarily unavailable. Please use the contact page if you need direct support.'}});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
$('#year').textContent=new Date().getFullYear();
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();closeAI()}});
