const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const PAYSTACK='https://paystack.shop/pay/speakout-donate',AI='https://us-central1-speaakout-portal.cloudfunctions.net/askJerry';
const intro=$('#intro');const closeIntro=()=>intro?.classList.add('done');$('#skipIntro')?.addEventListener('click',closeIntro);addEventListener('load',()=>setTimeout(closeIntro,5200));
const menu=$('#menu');const openMenu=()=>{menu.classList.add('open');menu.setAttribute('aria-hidden','false')},closeMenu=()=>{menu.classList.remove('open');menu.setAttribute('aria-hidden','true')};$('#openMenu')?.addEventListener('click',openMenu);$$('[data-close-menu]').forEach(x=>x.addEventListener('click',closeMenu));
const profile=$('#profileSheet');function openProfile(){profile.classList.add('open');profile.setAttribute('aria-hidden','false');navigator.vibrate?.(8)}function closeProfile(){profile.classList.remove('open');profile.setAttribute('aria-hidden','true')}$('#openProfile')?.addEventListener('click',openProfile);$('#quickProfile')?.addEventListener('click',openProfile);$$('[data-close-profile]').forEach(x=>x.addEventListener('click',closeProfile));
$$('[data-donate]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();open(PAYSTACK,'_blank','noopener,noreferrer')}));
$('#shareProfile')?.addEventListener('click',async()=>{const data={title:'Jerry Nnamdi Offorka',text:'Explore Jerry Nnamdi Offorka’s digital portfolio.',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);$('#shareProfile').textContent='Link copied'}}catch{}});
const aiModal=$('#aiModal'),aiMessages=$('#aiMessages'),aiQuestion=$('#aiQuestion');function openAI(){aiModal.classList.add('open');aiModal.setAttribute('aria-hidden','false');setTimeout(()=>aiQuestion?.focus(),120)}function closeAI(){aiModal.classList.remove('open');aiModal.setAttribute('aria-hidden','true')}$$('[data-open-ai]').forEach(x=>x.addEventListener('click',openAI));$$('[data-close-ai]').forEach(x=>x.addEventListener('click',closeAI));$$('[data-ai-prompt]').forEach(x=>x.addEventListener('click',()=>{aiQuestion.value=x.dataset.aiPrompt;aiQuestion.focus()}));
function msg(role,text){const d=document.createElement('div');d.className='ai-message '+role;d.textContent=text;aiMessages.append(d);aiMessages.scrollTop=aiMessages.scrollHeight;return d}$('#aiForm')?.addEventListener('submit',async e=>{e.preventDefault();const q=aiQuestion.value.trim();if(!q)return;msg('user',q);aiQuestion.value='';const thinking=msg('assistant','Thinking…');try{const r=await fetch(AI,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})}),d=await r.json();thinking.textContent=r.ok?(d.answer||'How else can I help?'):(d.error||'Jerry+ is temporarily unavailable.')}catch{thinking.textContent='Jerry+ is temporarily unavailable. Please use the contact or booking options.'}});
const hub=$('#hub'),light=$('#cursorLight');let raf;function ambient(e){if(innerWidth<700&&e.pointerType!=='pen')return;cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const x=e.clientX/innerWidth-.5,y=e.clientY/innerHeight-.5;hub.style.setProperty('--tiltX',`${x*5}deg`);hub.style.setProperty('--tiltY',`${y*-4}deg`);light.style.left=e.clientX+'px';light.style.top=e.clientY+'px'})}addEventListener('pointermove',ambient,{passive:true});
const joy=$('#joystick'),label=$('#joyLabel'),line=$('#energyLine');if(joy){const targets={up:{label:'Public Speaking',url:'speaking.html',el:$('.orb-up'),angle:-90},left:{label:'Leadership & Consulting',url:'consulting.html',el:$('.orb-left'),angle:180},right:{label:'Social Impact',url:'impact.html',el:$('.orb-right'),angle:0},down:{label:'Learning Hub',url:'media.html',el:$('.orb-down'),angle:90}};let start,drag=false,active=null,dist=0,lastActive=null;const direction=(dx,dy)=>Math.hypot(dx,dy)<30?null:Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');function setActive(dir){active=dir;Object.values(targets).forEach(t=>t.el.classList.remove('selected'));if(dir){const t=targets[dir];t.el.classList.add('selected');label.innerHTML=`<strong>${t.label}</strong><small>Release to explore</small>`;line.style.opacity='1';line.style.width='40%';line.style.transform=`rotate(${t.angle}deg)`;if(lastActive!==dir){navigator.vibrate?.(12);lastActive=dir}}else{label.innerHTML='<strong>Explore Jerry</strong><small>Drag toward a sphere</small>';line.style.opacity='0';line.style.width='0';lastActive=null}}joy.addEventListener('pointerdown',e=>{drag=true;start={x:e.clientX,y:e.clientY};dist=0;joy.setPointerCapture(e.pointerId);joy.style.animation='none';joy.style.transition='none';navigator.vibrate?.(8)});joy.addEventListener('pointermove',e=>{if(!drag)return;const rx=e.clientX-start.x,ry=e.clientY-start.y;dist=Math.hypot(rx,ry);const max=38,m=Math.max(1,dist),dx=m>max?rx/m*max:rx,dy=m>max?ry/m*max:ry;joy.style.transform=`translate3d(${dx}px,${dy}px,70px) rotateX(${-dy/7}deg) rotateY(${dx/7}deg) scale(1.025)`;joy.style.setProperty('--px',`${50+dx}%`);joy.style.setProperty('--py',`${50+dy}%`);setActive(direction(rx,ry))});function end(){if(!drag)return;drag=false;const chosen=active;joy.style.transition='transform .42s cubic-bezier(.18,.9,.2,1.15)';joy.style.transform='translate3d(0,0,0)';setTimeout(()=>joy.style.animation='',450);if(dist<12){openProfile();setActive(null);return}if(chosen)setTimeout(()=>location.href=targets[chosen].url,160);setTimeout(()=>setActive(null),280)}joy.addEventListener('pointerup',end);joy.addEventListener('pointercancel',end)}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();closeProfile();closeAI()}});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
