const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const CALL_LINK='tel:+2348118103510',PAYSTACK_DONATION_LINK='https://paystack.shop/pay/speakout-donate',FIREBASE_AI_ENDPOINT='https://us-central1-speaakout-portal.cloudfunctions.net/askJerry';
function applyTheme(t){document.documentElement.dataset.theme=t==='day'?'day':'';localStorage.setItem('offorka-theme',t);$$('.theme-action,.page-theme').forEach(btn=>{btn.textContent=t==='day'?'☀️':'🌙'})}
applyTheme(localStorage.getItem('offorka-theme')||'night');
$$('.theme-action,.page-theme').forEach(btn=>btn.addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='day'?'night':'day')));
const boot=$('#boot'),skipBoot=$('#skipBoot');function closeBoot(){boot?.classList.add('done')}skipBoot?.addEventListener('click',closeBoot);window.addEventListener('load',()=>setTimeout(closeBoot,5600));
const menuAction=$('#menuAction'),drawer=$('#drawer');menuAction?.addEventListener('click',()=>{drawer?.classList.add('open');drawer?.setAttribute('aria-hidden','false')});$$('[data-close-menu],.drawer-backdrop').forEach(el=>el.addEventListener('click',()=>{drawer?.classList.remove('open');drawer?.setAttribute('aria-hidden','true')}));
$$('[data-donate]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();window.open(PAYSTACK_DONATION_LINK,'_blank','noopener,noreferrer')}));
const aiModal=$('#aiModal'),aiMessages=$('#aiMessages'),aiQuestion=$('#aiQuestion');function openAI(){aiModal?.classList.add('open');aiModal?.setAttribute('aria-hidden','false');setTimeout(()=>aiQuestion?.focus(),100)}function closeAI(){aiModal?.classList.remove('open');aiModal?.setAttribute('aria-hidden','true')}$$('[data-open-ai]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openAI()}));$$('[data-close-ai],.modal-backdrop').forEach(el=>el.addEventListener('click',closeAI));
function addMessage(role,text){const div=document.createElement('div');div.className=`ai-message ${role}`;div.textContent=text;aiMessages?.appendChild(div);if(aiMessages)aiMessages.scrollTop=aiMessages.scrollHeight}
$('#aiForm')?.addEventListener('submit',async e=>{e.preventDefault();const question=aiQuestion.value.trim();if(!question)return;addMessage('user',question);aiQuestion.value='';addMessage('assistant','Thinking...');try{const response=await fetch(FIREBASE_AI_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const data=await response.json();const replies=$$('.ai-message.assistant',aiMessages);const lastReply=replies[replies.length-1];lastReply.textContent=response.ok?(data.answer||'I’m here with you. Could you share a little more?'):(data.error||'Jerry+ is temporarily unavailable.')}catch{const replies=$$('.ai-message.assistant',aiMessages);const lastReply=replies[replies.length-1];lastReply.textContent='Jerry+ is not connected yet. Deploy the Firebase function to activate live AI.'}});
const analog=$('#analog');if(analog){const chip=$('#analogChip');const targets={up:{label:'Public Speaking',url:'speaking.html',el:$('.up')},left:{label:'Leadership & Consulting',url:'consulting.html',el:$('.left')},right:{label:'Learning Hub',url:'media.html',el:$('.right')},down:{label:'Donate',donate:true,el:$('.down')}};let start=null,dragging=false,active=null,distance=0;function resetChip(){if(!chip)return;chip.innerHTML='<strong>Tap to Call</strong><small>Drag to explore</small>'}function setActive(directionName){active=directionName;Object.values(targets).forEach(target=>target.el?.classList.remove('selected'));if(directionName&&targets[directionName]){targets[directionName].el?.classList.add('selected');if(chip){chip.innerHTML=`<strong>${targets[directionName].label}</strong><small>Release to open</small>`}}else resetChip()}function getDirection(dx,dy){const dist=Math.hypot(dx,dy);if(dist<32)return null;if(Math.abs(dx)>Math.abs(dy))return dx>0?'right':'left';return dy>0?'down':'up'}analog.addEventListener('pointerdown',e=>{if(navigator.vibrate)navigator.vibrate(8);dragging=true;active=null;distance=0;start={x:e.clientX,y:e.clientY};analog.setPointerCapture(e.pointerId);analog.style.transition='none'});analog.addEventListener('pointermove',e=>{if(!dragging||!start)return;const rawDx=e.clientX-start.x,rawDy=e.clientY-start.y;distance=Math.hypot(rawDx,rawDy);let dx=rawDx,dy=rawDy;const max=36,mag=Math.max(1,distance);if(mag>max){dx=(dx/mag)*max;dy=(dy/mag)*max}analog.style.transform=`translate3d(${dx}px, ${dy}px, 68px) rotateX(${-dy/7}deg) rotateY(${dx/7}deg) scale(1.025)`;analog.style.setProperty('--px',`${50+dx}%`);analog.style.setProperty('--py',`${50+dy}%`);setActive(getDirection(rawDx,rawDy))});function endAnalog(){if(!dragging)return;dragging=false;const chosen=active;analog.style.transition='transform .34s cubic-bezier(.18,.9,.22,1.15)';analog.style.transform='translate3d(0,0,0) rotateX(0deg) rotateY(0deg)';if(distance<12){location.href=CALL_LINK;return}if(chosen&&targets[chosen]){setTimeout(()=>{if(targets[chosen].donate)window.open(PAYSTACK_DONATION_LINK,'_blank','noopener,noreferrer');else location.href=targets[chosen].url},150)}setTimeout(()=>setActive(null),250)}analog.addEventListener('pointerup',endAnalog);analog.addEventListener('pointercancel',endAnalog)}
document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;drawer?.classList.remove('open');drawer?.setAttribute('aria-hidden','true');aiModal?.classList.remove('open');aiModal?.setAttribute('aria-hidden','true')});