const $=(s,root=document)=>root.querySelector(s);const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const themes=['midnight','sunrise','aurora','forest']; const themeIcons={midnight:'🌙',sunrise:'☀️',aurora:'✨',forest:'🌿'}; const CALL_LINK='tel:+2348118103510';
function applyTheme(t){const theme=themes.includes(t)?t:'midnight';document.documentElement.dataset.theme=theme==='midnight'?'':theme;localStorage.setItem('offorka-theme',theme);const btn=$('.theme-btn');if(btn)btn.textContent=themeIcons[theme];}
applyTheme(localStorage.getItem('offorka-theme')||'midnight');
window.addEventListener('load',()=>{setTimeout(()=>$('.preloader')?.classList.add('done'),700); if(!localStorage.getItem('offorka-welcome-seen')) setTimeout(()=>$('#welcomeModal')?.classList.add('open'),900);});
$('.theme-btn')?.addEventListener('click',()=>{const cur=localStorage.getItem('offorka-theme')||'midnight';applyTheme(themes[(themes.indexOf(cur)+1)%themes.length]);});
$('[data-open-launcher]')?.addEventListener('click',()=>$('#launcher')?.classList.add('open')); $$('[data-close-launcher],.launcher-close').forEach(b=>b.addEventListener('click',()=>$('#launcher')?.classList.remove('open')));
$$('[data-close-welcome]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('offorka-welcome-seen','1');$('#welcomeModal')?.classList.remove('open')}));
const reflections=['Every meaningful change begins with a conversation.','Strong minds create stronger communities.','Healing begins when people feel heard.','Compassion is the beginning of leadership.','Every voice deserves hope.'];
const ref=$('#dailyReflection'); if(ref){let i=new Date().getDate()%reflections.length;ref.textContent=reflections[i];setInterval(()=>{i=(i+1)%reflections.length;ref.animate([{opacity:.25,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],{duration:420,easing:'ease-out'});ref.textContent=reflections[i];},10000)}
const portrait=$('#portraitControl'); if(portrait){const nodes={up:$('.node-up'),left:$('.node-left'),right:$('.node-right'),down:$('.node-down')};const labels={up:'Public Speaking',left:'Leadership & Consulting',right:'Learning Hub',down:'Book a Session'};const urls={up:'speaking.html',left:'consulting.html',right:'media.html',down:'booking.html'};const label=$('#activeLabel');let start=null,active=null,dragging=false,dragDistance=0;
function setActive(dir){active=dir;Object.values(nodes).forEach(n=>n?.classList.remove('active'));if(dir){nodes[dir]?.classList.add('active');if(label)label.innerHTML=`Release to open<small>${labels[dir]}</small>`;}else if(label){label.innerHTML=`Let's Connect<small>Tap to call · Drag to explore</small>`;}}
function getDirection(dx,dy){const d=Math.hypot(dx,dy);if(d<32)return null;return Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up')}
portrait.addEventListener('pointerdown',e=>{dragging=true;dragDistance=0;active=null;start={x:e.clientX,y:e.clientY};portrait.setPointerCapture(e.pointerId);portrait.style.transition='none'});
portrait.addEventListener('pointermove',e=>{if(!dragging||!start)return;let dx=e.clientX-start.x,dy=e.clientY-start.y;dragDistance=Math.hypot(dx,dy);const max=40,mag=Math.max(1,Math.hypot(dx,dy));if(mag>max){dx=dx/mag*max;dy=dy/mag*max}portrait.style.transform=`translate(${dx}px,${dy}px) rotateX(${-dy/7}deg) rotateY(${dx/7}deg)`;portrait.style.setProperty('--px',`${50+dx}%`);portrait.style.setProperty('--py',`${50+dy}%`);setActive(getDirection(e.clientX-start.x,e.clientY-start.y));});
function end(){if(!dragging)return;dragging=false;const chosen=active,wasTap=!chosen&&dragDistance<12;portrait.style.transition='transform .34s cubic-bezier(.18,.9,.22,1.15)';portrait.style.transform='translate(0,0) rotateX(0) rotateY(0)';setTimeout(()=>{setActive(null);portrait.style.transition=''},220);if(wasTap){setTimeout(()=>{location.href=CALL_LINK},120);return}if(chosen)setTimeout(()=>{location.href=urls[chosen]},180)}
portrait.addEventListener('pointerup',end);portrait.addEventListener('pointercancel',end);setActive(null)}
const ai=$('#askJerryInput'); if(ai){const out=$('#askJerryOutput');ai.addEventListener('input',()=>{const v=ai.value.toLowerCase();let msg='Ask Jerry is being prepared. Soon, this space will guide visitors to books, talks, resources and booking options.';if(v.includes('anxiety')||v.includes('stress'))msg='Coming soon: educational guidance for stress and anxiety, with resources and consultation options.';if(v.includes('speaker')||v.includes('event'))msg='Coming soon: speaking recommendations, topic matching and invitation guidance.';if(out)out.textContent=msg;});}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
